### ISSUE TITLE
[UMBRELLA] Review/expand contribution guidance

### ISSUE THREAD

**Issue by justaugustus** [ossf/scorecard#1553]
I've left a few reviews/comments here and there on PRs and it's worth reviewing contribution guidelines, just to ensure everyone has the tools they need to effectively contribute to the project.

To be clear, we've got a lot of great documentation today.
Let's see if we can get even better!

Eventually, this could be abstracted as general guidance for all OpenSSF projects, similar to https://github.com/kubernetes/community.

For current and potential contributors/maintainers, please feel free to leave comments about what kind of doc improvements you'd like to see.

- [ ] Contributor ladder: https://github.com/ossf/scorecard/issues/1529 / https://github.com/ossf/scorecard/issues/308
- [ ] Contributor review guidance: https://github.com/ossf/scorecard/issues/1552
- [ ] Code signoffs: https://github.com/ossf/scorecard/issues/1533
- [ ] Handling copyright dates: https://github.com/ossf/scorecard/issues/1534
- [ ] Releasing:
  - [ ] Use Kubernetes `release-notes` tool for releases: https://github.com/ossf/scorecard/issues/1676
  - [ ] Document scorecard release processes: https://github.com/ossf/scorecard/issues/1677

cc: @azeemshaikh38 @inferno-chromium @justaugustus @laurentsimon @naveensrinivasan @olivekl @david-a-wheeler @jeffmendoza @vmbrasseur

**Comment by annabellegoth2boss** [comment]
I opened a related [issue](https://github.com/ossf/foundation/issues/17) under the /foundation repo; not sure if that's the right place, but maybe has more "umbrella" scope?

**Comment by justaugustus** [comment]
> I opened a related [issue](https://github.com/ossf/foundation/issues/17) under the /foundation repo; not sure if that's the right place, but maybe has more "across-all-of-OSSF" scope?

Liked, subscribed, and hit the bell!
Thanks for cross-linking these, @annabellegoth2boss!

**Comment by spencerschrock** [comment]
I believe most of these tasks are completed at this point in time.
